variables:
  STEAM_CI_DEPENDENCIES: >-
    clang
    dbus
    gcovr
    glib2-devel
    json-glib
    lcov
    meson
    ninja
    polkit
    valgrind
    python-dbusmock
    python-packaging

stages:
  - build

.build:
  stage: build
  tags:
    - x86_64-linux-kvm-docker
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/archlinux:base-devel
  script:
    - |
      set -eux

      pacman -Syu --needed --noconfirm --noprogressbar \
      ${STEAM_CI_DEPENDENCIES}

      # By setting this env var we can start new D-Bus services
      export DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --fork --config-file=/usr/share/dbus-1/session.conf --print-address`
      # A new system bus is needed for the mock polkit
      export DBUS_SYSTEM_BUS_ADDRESS=`dbus-daemon --fork --config-file=ci/dbus_system.conf --print-address`

      export CC=${COMPILER}
      export CXX=${COMPILER}++

      meson \
        --werror \
        -Db_lundef=${LUNDEF} \
        -Db_sanitize=${SANITIZER} \
        -Dusing_valgrind=${VALGRIND:-false} \
        -Db_coverage=${COVERAGE:-false} \
        _build
      ninja -C _build
      ninja -C _build install

      # Do not run multiple tests in parallel because they all rely on the same
      # D-Bus path, so they'll conflict with each other
      if [ -z "${VALGRIND-}" ]; then
        meson test --verbose -C _build
      else
        export DEBUGINFOD_URLS=https://debuginfod.archlinux.org
        meson test --wrap='valgrind --trace-children=yes --error-exitcode=1' --verbose -C _build
      fi

  artifacts:
    paths:
      - _build/meson-logs/*.txt
    when: always

build:gcc_with_coverage:
  extends: .build
  variables:
    COMPILER: "gcc"
    COVERAGE: "true"
    LUNDEF: "true"
    SANITIZER: "none"
  after_script:
    # We don't use coverage-html because it exits with an error about "duplicate merge record atomupd-daemon"
    - lcov --capture --directory _build --output-file _build/meson-logs/coverage.info
    - genhtml _build/meson-logs/coverage.info --output-directory _build/meson-logs/coverage_report
    - ninja -C _build coverage-xml
  coverage: '/^\s+lines.+:\s+([\d.]+\%)\s+/'
  artifacts:
    paths:
      - _build/meson-logs
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: _build/meson-logs/coverage.xml

build:gcc_asan:
  extends: .build
  variables:
    COMPILER: "gcc"
    LUNDEF: "false"
    SANITIZER: "address,undefined"

build:clang:
  extends: .build
  variables:
    COMPILER: "clang"
    LUNDEF: "true"
    SANITIZER: "none"

build:clang_asan:
  extends: .build
  variables:
    COMPILER: "clang"
    LUNDEF: "false"
    # FIXME `undefined` has been removed because it fails with:
    # "call to function (unknown) through pointer to incorrect function type"
    # It could be a false positive, or something odd in gdbus-codegen.
    SANITIZER: "address"

build:valgrind:
  extends: .build
  # FIXME this step is not yet entirely reliable
  allow_failure: true
  variables:
    COMPILER: "gcc"
    LUNDEF: "true"
    SANITIZER: "none"
    VALGRIND: "true"
