variables:
  STEAM_CI_DEPENDENCIES: >-
    clang
    meson
    ninja

stages:
  - build

.build:
  stage: build
  tags:
    - docker
    - linux
  image: archlinux:base-devel
  script:
    - |
      set -eux

      pacman -Syu --needed --noconfirm --noprogressbar \
      ${STEAM_CI_DEPENDENCIES}

      export CC=${COMPILER}
      export CXX=${COMPILER}++

      meson \
        --werror \
        -Db_lundef=${LUNDEF} \
        -Db_sanitize=${SANITIZER} \
        _build
      ninja -C _build
      ninja -C _build install
      meson test --verbose -C _build

  artifacts:
    paths:
      - _build/meson-logs/*.txt
    when: always

build:devel:
  extends: .build
  variables:
    COMPILER: "gcc"
    LUNDEF: "true"
    SANITIZER: "none"

build:clang:
  extends: .build
  variables:
    COMPILER: "clang"
    LUNDEF: "false"
    SANITIZER: "address,undefined"
