variables:
  STEAM_CI_DEPENDENCIES: >-
    clang
    meson
    ninja

stages:
  - build

build:devel:
  stage: build
  tags:
    - docker
    - linux
  image: archlinux:base-devel
  script:
    - |
      set -eux

      pacman -Syu --needed --noconfirm --noprogressbar \
      ${STEAM_CI_DEPENDENCIES}

      mkdir -p _build
      meson \
        --werror \
        _build/devel
      ninja -C _build/devel
      ninja -C _build/devel install
      meson test --verbose -C _build/devel

  artifacts:
    paths:
      - _build/devel/meson-logs/*.txt
    when: always

build:clang:
  stage: build
  tags:
    - docker
    - linux
  image: archlinux:base-devel
  script:
    - |
      set -eux

      pacman -Syu --needed --noconfirm --noprogressbar \
      ${STEAM_CI_DEPENDENCIES}

      export CC=clang
      export CXX=clang++

      meson \
        -Db_lundef=false \
        -Db_sanitize=address,undefined \
        --werror \
        _build/clang-asan
      ninja -C _build/clang-asan
      ninja -C _build/clang-asan install
      meson test --verbose -C _build/clang-asan

  artifacts:
    paths:
      - _build/clang-asan/meson-logs/*.txt
    when: always
